services:
  - type: worker
    name: solana-sniper-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    envVars:
      - key: PRIVATE_KEY
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
      - key: MAIN_WITHDRAW_WALLET
        sync: false
      - key: JUPITER_API_KEY
        sync: false
